const userss = [
  { userId: 1, email: "admin1@gmail.com", roles: "ADMIN" },
  { userId: 2, email: "admin2@gmail.com", roles: "ADMIN" },
  { userId: 3, email: "admin3@gmail.com", roles: "ADMIN" },
  { userId: 4, email: "user1@gmail.com", roles: "USER" },
  { userId: 5, email: "user2@gmail.com", roles: "USER" },
  { userId: 6, email: "user3@gmail.com", roles: "USER" },
  { userId: 7, email: "user4@gmail.com", roles: "USER" },
  { userId: 8, email: "user5@gmail.com", roles: "USER" },
  { userId: 9, email: "user6@gmail.com", roles: "USER" },
  { userId: 10, email: "user7@gmail.com", roles: "USER" },
  { userId: 11, email: "user8@gmail.com", roles: "USER" },
  { userId: 12, email: "user9@gmail.com", roles: "USER" },
  { userId: 13, email: "user10@gmail.com", roles: "USER" },
  { userId: 14, email: "user11@gmail.com", roles: "USER" },
  { userId: 15, email: "user12@gmail.com", roles: "USER" },
  { userId: 16, email: "user13@gmail.com", roles: "USER" },
  { userId: 17, email: "user14@gmail.com", roles: "USER" },
  { userId: 18, email: "user15@gmail.com", roles: "USER" },
  { userId: 19, email: "user16@gmail.com", roles: "USER" },
  { userId: 20, email: "user17@gmail.com", roles: "USER" },
  { userId: 21, email: "user18@gmail.com", roles: "USER" },
  { userId: 22, email: "user19@gmail.com", roles: "USER" },
  { userId: 23, email: "user20@gmail.com", roles: "USER" },
  { userId: 24, email: "user21@gmail.com", roles: "USER" },
  { userId: 25, email: "user22@gmail.com", roles: "USER" },
  { userId: 26, email: "user23@gmail.com", roles: "USER" },
];
export default userss;
