/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "on-surface-variant": "#43474e",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#adc7f7",
        "tertiary-fixed": "#ffddba",
        "secondary-container": "#a2eded",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#002020",
        "inverse-surface": "#2d3133",
        "secondary-fixed": "#a5eff0",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#c6955e",
        "surface-tint": "#455f88",
        "secondary": "#13696a",
        "primary-fixed": "#d6e3ff",
        "on-primary-container": "#86a0cd",
        "on-error": "#ffffff",
        "on-secondary-container": "#1a6d6e",
        "surface-container": "#eceef0",
        "tertiary-fixed-dim": "#f2bc82",
        "primary": "#002045",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-primary": "#adc7f7",
        "tertiary": "#321b00",
        "secondary-fixed-dim": "#89d3d4",
        "error": "#ba1a1a",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea",
        "outline": "#74777f",
        "on-tertiary-fixed": "#2b1700",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-primary-fixed-variant": "#2d476f",
        "tertiary-container": "#4f2e00",
        "background": "#f7f9fb",
        "on-error-container": "#93000a",
        "primary-container": "#1a365d",
        "on-tertiary-fixed-variant": "#633f0f",
        "on-surface": "#191c1e",
        "on-primary-fixed": "#001b3c",
        "outline-variant": "#c4c6cf",
        "on-secondary-fixed-variant": "#004f50",
        "inverse-on-surface": "#eff1f3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "manrope": ["Manrope"]
      }
    },
  },
  plugins: [],
}