spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanlytuyendung_nhom10
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # 3. Cấu hình Keycloak (Xác minh Token)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/WebTuyenDung
idp:
  url: ${KEYCLOAK_URL:http://localhost:8180}
  client-id: webtuyendung_id
  client-secret: P36Z4mKCskPez0VD1vud4IXu6HUdasTa